### ISSUE TITLE
添加可以控制取词的开关

### ISSUE THREAD

**Issue by langren1353** [HalfdogStudio/youdaodict#1]
用着好用，不过希望来一个可以控制的开关，不然选中啥都会被翻译掉
手残党表示会经常在页面双击，弹出的这种东西感觉很忧伤，觉得如果有个开关的话不怎么爽
感谢感谢

**Comment by reverland** [comment]
可以试试 ctrlkey分支

https://github.com/HalfdogStudio/youdaodict/blob/ctrlkey/youdaodict.user.js

按下ctrl键再取词。

如果有什么问题请仍在该issue反馈。

**Comment by langren1353** [comment]
1.master分支中 README.md添加表示存在其他分支，一般人来看看就只会看默认master分支
2.来个alt分支吧，虽然代码都差不多，发现ctrl有好多脚本都占用了

**Comment by reverland** [comment]
@langren1353 哈哈，alt会和桌面环境冲突。

在linux下，一般桌面环境中alt+鼠标左键会移动窗口。。。

**Comment by langren1353** [comment]
@reverland 噗，原来是这样，勉强加上再写个说明吧，顺便更新下https://greasyfork.org/zh-CN/scripts/12758

**Comment by reverland** [comment]
@langren1353  不急吧，你可以暂时改源码改成任意键。

可能考虑
1. 设置快捷键开关
2. 像 https://greasyfork.org/en/scripts/6303-iciba%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91 这样的方式

我个人倾向于第一种，但是快捷键太多了。。。

**Comment by langren1353** [comment]
@reverland 尊重主权~
表示如果你增加上的话多一个选择，这样更开心 O_O
快捷键开关不会玩，不知道咋调用，反正你就随便搞一个alt版本丢在那里就行了
快捷键的还要去不断的选择开关，alt的windows下随便玩linux的你老老实实用ctrl就好了O_O

**Comment by reverland** [comment]
@langren1353 准备在master上推送shortcut分支

默认开启取词模式，可使用<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>q</kbd>关闭取词。

如果想要默认关闭，请自行把

https://github.com/HalfdogStudio/youdaodict/blob/shortcut-toggle/youdaodict.user.js#L14

从

```
var toggle = true;
```

改成

```
var toggle = false;
```

**Comment by langren1353** [comment]
我就只想问一句，情景：假设我是个不懂英语的中国人，More info on this article(in Chinese)是啥意思来着
O_O，我来卖萌的，就像好多软件的语言选择中都是Chinese，然而我根本不知道Chinese是啥意思来着

**Comment by reverland** [comment]
@langren1353 哈哈，那他就不会看
