### ISSUE TITLE
how to use??

### ISSUE THREAD

**Issue by lkasdolka** [HalfdogStudio/youdaodict#3]
这个怎么用啊，把js代码嵌入到浏览器的某处？？

**Comment by reverland** [comment]
@lkasdolka 浏览器支持Userscript，只是，用到了些扩展的功能。
- firefox： GreaseMonkey，scriptish
- chrome：Tampermonkey
- opera： 搞不清楚

**Comment by lkasdolka** [comment]
已搞定，比之前用过的插件好用~

459127552@qq.com

From: reverland
Date: 2015-11-26 09:20
To: HalfdogStudio/youdaodict
CC: Andy Liu
Subject: Re: [youdaodict] how to use?? (#3)
@lkasdolka 浏览器支持Userscript，只是，用到了些扩展的功能。
firefox： GreaseMonkey，scriptish
chrome：Tampermonkey
- opera： 高不清楚

**Comment by reverland** [comment]
@lkasdolka 233，扩展权限高
